### ISSUE TITLE
Repo ismi

### ISSUE THREAD

**Issue by Egesabanci** [HarunAGCA/multiprocessing-multithreading#1]
Harun merhaba, Github profiline Linkedin'de denk geldim, repolarını inceliyordum. 

Sanırım "Distributed Systems" ismi bu repo için pek doğru olmamış, multiprocessing ve threading; hesaplama yükünün **tek bir** bilgisayarın ilgili donanımlarına paylaştırılarak veya runtime'da çeşitli sıralar halinde işlenerek hafifletilmesi prensibine dayanıyor. Fakat "Distributed System"ler bundan çok daha farklı olarak, bir ağ üzerinde haberleşen **tamamen ayrı** yapılar olarak ele alınıyor.

Repo ismini düzenlemen, repoyu inceleyenler için daha doğru yönlendirme olabilir ve daha iyi bir izlenim yaratabilir.

Başarılar dilerim, kolay gelsin.

**Comment by HarunAGCA** [comment]
Merhaba,

Repo ismi konusunda haklısınız. Dağıtık sistemler dersi için yaptığım uygulamaları atmak için bu repoyu oluşturmuştum. Fakat sadece multiprocessing ve multithreading kodlarını atınca isim biraz yanıltıcı olmuş. İsmi düzenledim. 

Geri bildiriminiz için teşekkürler.

İyi çalışmalar.
